// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: cilium/api/isds.proto

package cilium

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on IdentitySelector with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IdentitySelector) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IdentitySelector with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IdentitySelectorMultiError, or nil if none found.
func (m *IdentitySelector) ValidateAll() error {
	return m.validate(true)
}

func (m *IdentitySelector) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	if len(m.GetIdentities()) < 1 {
		err := IdentitySelectorValidationError{
			field:  "Identities",
			reason: "value must contain at least 1 item(s)",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	_IdentitySelector_Identities_Unique := make(map[uint32]struct{}, len(m.GetIdentities()))

	for idx, item := range m.GetIdentities() {
		_, _ = idx, item

		if _, exists := _IdentitySelector_Identities_Unique[item]; exists {
			err := IdentitySelectorValidationError{
				field:  fmt.Sprintf("Identities[%v]", idx),
				reason: "repeated value must contain unique items",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		} else {
			_IdentitySelector_Identities_Unique[item] = struct{}{}
		}

		// no validation rules for Identities[idx]
	}

	if len(errors) > 0 {
		return IdentitySelectorMultiError(errors)
	}

	return nil
}

// IdentitySelectorMultiError is an error wrapping multiple validation errors
// returned by IdentitySelector.ValidateAll() if the designated constraints
// aren't met.
type IdentitySelectorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IdentitySelectorMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IdentitySelectorMultiError) AllErrors() []error { return m }

// IdentitySelectorValidationError is the validation error returned by
// IdentitySelector.Validate if the designated constraints aren't met.
type IdentitySelectorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdentitySelectorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdentitySelectorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdentitySelectorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdentitySelectorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdentitySelectorValidationError) ErrorName() string { return "IdentitySelectorValidationError" }

// Error satisfies the builtin error interface
func (e IdentitySelectorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIdentitySelector.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdentitySelectorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdentitySelectorValidationError{}

// Validate checks the field values on IdentitySelectorsConfigDump with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IdentitySelectorsConfigDump) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IdentitySelectorsConfigDump with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IdentitySelectorsConfigDumpMultiError, or nil if none found.
func (m *IdentitySelectorsConfigDump) ValidateAll() error {
	return m.validate(true)
}

func (m *IdentitySelectorsConfigDump) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetIdentityselectors() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IdentitySelectorsConfigDumpValidationError{
						field:  fmt.Sprintf("Identityselectors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IdentitySelectorsConfigDumpValidationError{
						field:  fmt.Sprintf("Identityselectors[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IdentitySelectorsConfigDumpValidationError{
					field:  fmt.Sprintf("Identityselectors[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return IdentitySelectorsConfigDumpMultiError(errors)
	}

	return nil
}

// IdentitySelectorsConfigDumpMultiError is an error wrapping multiple
// validation errors returned by IdentitySelectorsConfigDump.ValidateAll() if
// the designated constraints aren't met.
type IdentitySelectorsConfigDumpMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IdentitySelectorsConfigDumpMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IdentitySelectorsConfigDumpMultiError) AllErrors() []error { return m }

// IdentitySelectorsConfigDumpValidationError is the validation error returned
// by IdentitySelectorsConfigDump.Validate if the designated constraints
// aren't met.
type IdentitySelectorsConfigDumpValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IdentitySelectorsConfigDumpValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IdentitySelectorsConfigDumpValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IdentitySelectorsConfigDumpValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IdentitySelectorsConfigDumpValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IdentitySelectorsConfigDumpValidationError) ErrorName() string {
	return "IdentitySelectorsConfigDumpValidationError"
}

// Error satisfies the builtin error interface
func (e IdentitySelectorsConfigDumpValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIdentitySelectorsConfigDump.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IdentitySelectorsConfigDumpValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IdentitySelectorsConfigDumpValidationError{}
