// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: cilium/api/isds.proto

package cilium

import (
	context "context"
	_ "github.com/envoyproxy/go-control-plane/envoy/annotations"
	v3 "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentitySelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the identity selector.
	Key uint64 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	// Identities selected by this selector
	Identities    []uint32 `protobuf:"varint,2,rep,packed,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySelector) Reset() {
	*x = IdentitySelector{}
	mi := &file_cilium_api_isds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySelector) ProtoMessage() {}

func (x *IdentitySelector) ProtoReflect() protoreflect.Message {
	mi := &file_cilium_api_isds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySelector.ProtoReflect.Descriptor instead.
func (*IdentitySelector) Descriptor() ([]byte, []int) {
	return file_cilium_api_isds_proto_rawDescGZIP(), []int{0}
}

func (x *IdentitySelector) GetKey() uint64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *IdentitySelector) GetIdentities() []uint32 {
	if x != nil {
		return x.Identities
	}
	return nil
}

type IdentitySelectorsConfigDump struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Identityselectors []*IdentitySelector    `protobuf:"bytes,1,rep,name=identityselectors,proto3" json:"identityselectors,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IdentitySelectorsConfigDump) Reset() {
	*x = IdentitySelectorsConfigDump{}
	mi := &file_cilium_api_isds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySelectorsConfigDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySelectorsConfigDump) ProtoMessage() {}

func (x *IdentitySelectorsConfigDump) ProtoReflect() protoreflect.Message {
	mi := &file_cilium_api_isds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySelectorsConfigDump.ProtoReflect.Descriptor instead.
func (*IdentitySelectorsConfigDump) Descriptor() ([]byte, []int) {
	return file_cilium_api_isds_proto_rawDescGZIP(), []int{1}
}

func (x *IdentitySelectorsConfigDump) GetIdentityselectors() []*IdentitySelector {
	if x != nil {
		return x.Identityselectors
	}
	return nil
}

var File_cilium_api_isds_proto protoreflect.FileDescriptor

const file_cilium_api_isds_proto_rawDesc = "" +
	"\n" +
	"\x15cilium/api/isds.proto\x12\x06cilium\x1a*envoy/service/discovery/v3/discovery.proto\x1a\x1cgoogle/api/annotations.proto\x1a envoy/annotations/resource.proto\x1a\x17validate/validate.proto\"P\n" +
	"\x10IdentitySelector\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12*\n" +
	"\n" +
	"identities\x18\x02 \x03(\rB\n" +
	"\xfaB\a\x92\x01\x04\b\x01\x18\x01R\n" +
	"identities\"e\n" +
	"\x1bIdentitySelectorsConfigDump\x12F\n" +
	"\x11identityselectors\x18\x01 \x03(\v2\x18.cilium.IdentitySelectorR\x11identityselectors2\xed\x03\n" +
	" IdentitySelectorDiscoveryService\x12|\n" +
	"\x17StreamIdentitySelectors\x12,.envoy.service.discovery.v3.DiscoveryRequest\x1a-.envoy.service.discovery.v3.DiscoveryResponse\"\x00(\x010\x01\x12\x85\x01\n" +
	"\x16DeltaIdentitySelectors\x121.envoy.service.discovery.v3.DeltaDiscoveryRequest\x1a2.envoy.service.discovery.v3.DeltaDiscoveryResponse\"\x00(\x010\x01\x12\xa1\x01\n" +
	"\x16FetchIdentitySelectors\x12,.envoy.service.discovery.v3.DiscoveryRequest\x1a-.envoy.service.discovery.v3.DiscoveryResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v2/discovery:identity_selector\x1a\x1f\x8a\xa4\x96\xf3\a\x19\n" +
	"\x17cilium.IdentitySelectorB.Z,github.com/cilium/proxy/go/cilium/api;ciliumb\x06proto3"

var (
	file_cilium_api_isds_proto_rawDescOnce sync.Once
	file_cilium_api_isds_proto_rawDescData []byte
)

func file_cilium_api_isds_proto_rawDescGZIP() []byte {
	file_cilium_api_isds_proto_rawDescOnce.Do(func() {
		file_cilium_api_isds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cilium_api_isds_proto_rawDesc), len(file_cilium_api_isds_proto_rawDesc)))
	})
	return file_cilium_api_isds_proto_rawDescData
}

var file_cilium_api_isds_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cilium_api_isds_proto_goTypes = []any{
	(*IdentitySelector)(nil),            // 0: cilium.IdentitySelector
	(*IdentitySelectorsConfigDump)(nil), // 1: cilium.IdentitySelectorsConfigDump
	(*v3.DiscoveryRequest)(nil),         // 2: envoy.service.discovery.v3.DiscoveryRequest
	(*v3.DeltaDiscoveryRequest)(nil),    // 3: envoy.service.discovery.v3.DeltaDiscoveryRequest
	(*v3.DiscoveryResponse)(nil),        // 4: envoy.service.discovery.v3.DiscoveryResponse
	(*v3.DeltaDiscoveryResponse)(nil),   // 5: envoy.service.discovery.v3.DeltaDiscoveryResponse
}
var file_cilium_api_isds_proto_depIdxs = []int32{
	0, // 0: cilium.IdentitySelectorsConfigDump.identityselectors:type_name -> cilium.IdentitySelector
	2, // 1: cilium.IdentitySelectorDiscoveryService.StreamIdentitySelectors:input_type -> envoy.service.discovery.v3.DiscoveryRequest
	3, // 2: cilium.IdentitySelectorDiscoveryService.DeltaIdentitySelectors:input_type -> envoy.service.discovery.v3.DeltaDiscoveryRequest
	2, // 3: cilium.IdentitySelectorDiscoveryService.FetchIdentitySelectors:input_type -> envoy.service.discovery.v3.DiscoveryRequest
	4, // 4: cilium.IdentitySelectorDiscoveryService.StreamIdentitySelectors:output_type -> envoy.service.discovery.v3.DiscoveryResponse
	5, // 5: cilium.IdentitySelectorDiscoveryService.DeltaIdentitySelectors:output_type -> envoy.service.discovery.v3.DeltaDiscoveryResponse
	4, // 6: cilium.IdentitySelectorDiscoveryService.FetchIdentitySelectors:output_type -> envoy.service.discovery.v3.DiscoveryResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cilium_api_isds_proto_init() }
func file_cilium_api_isds_proto_init() {
	if File_cilium_api_isds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cilium_api_isds_proto_rawDesc), len(file_cilium_api_isds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cilium_api_isds_proto_goTypes,
		DependencyIndexes: file_cilium_api_isds_proto_depIdxs,
		MessageInfos:      file_cilium_api_isds_proto_msgTypes,
	}.Build()
	File_cilium_api_isds_proto = out.File
	file_cilium_api_isds_proto_goTypes = nil
	file_cilium_api_isds_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// IdentitySelectorDiscoveryServiceClient is the client API for IdentitySelectorDiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentitySelectorDiscoveryServiceClient interface {
	StreamIdentitySelectors(ctx context.Context, opts ...grpc.CallOption) (IdentitySelectorDiscoveryService_StreamIdentitySelectorsClient, error)
	DeltaIdentitySelectors(ctx context.Context, opts ...grpc.CallOption) (IdentitySelectorDiscoveryService_DeltaIdentitySelectorsClient, error)
	FetchIdentitySelectors(ctx context.Context, in *v3.DiscoveryRequest, opts ...grpc.CallOption) (*v3.DiscoveryResponse, error)
}

type identitySelectorDiscoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentitySelectorDiscoveryServiceClient(cc grpc.ClientConnInterface) IdentitySelectorDiscoveryServiceClient {
	return &identitySelectorDiscoveryServiceClient{cc}
}

func (c *identitySelectorDiscoveryServiceClient) StreamIdentitySelectors(ctx context.Context, opts ...grpc.CallOption) (IdentitySelectorDiscoveryService_StreamIdentitySelectorsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IdentitySelectorDiscoveryService_serviceDesc.Streams[0], "/cilium.IdentitySelectorDiscoveryService/StreamIdentitySelectors", opts...)
	if err != nil {
		return nil, err
	}
	x := &identitySelectorDiscoveryServiceStreamIdentitySelectorsClient{stream}
	return x, nil
}

type IdentitySelectorDiscoveryService_StreamIdentitySelectorsClient interface {
	Send(*v3.DiscoveryRequest) error
	Recv() (*v3.DiscoveryResponse, error)
	grpc.ClientStream
}

type identitySelectorDiscoveryServiceStreamIdentitySelectorsClient struct {
	grpc.ClientStream
}

func (x *identitySelectorDiscoveryServiceStreamIdentitySelectorsClient) Send(m *v3.DiscoveryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *identitySelectorDiscoveryServiceStreamIdentitySelectorsClient) Recv() (*v3.DiscoveryResponse, error) {
	m := new(v3.DiscoveryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *identitySelectorDiscoveryServiceClient) DeltaIdentitySelectors(ctx context.Context, opts ...grpc.CallOption) (IdentitySelectorDiscoveryService_DeltaIdentitySelectorsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IdentitySelectorDiscoveryService_serviceDesc.Streams[1], "/cilium.IdentitySelectorDiscoveryService/DeltaIdentitySelectors", opts...)
	if err != nil {
		return nil, err
	}
	x := &identitySelectorDiscoveryServiceDeltaIdentitySelectorsClient{stream}
	return x, nil
}

type IdentitySelectorDiscoveryService_DeltaIdentitySelectorsClient interface {
	Send(*v3.DeltaDiscoveryRequest) error
	Recv() (*v3.DeltaDiscoveryResponse, error)
	grpc.ClientStream
}

type identitySelectorDiscoveryServiceDeltaIdentitySelectorsClient struct {
	grpc.ClientStream
}

func (x *identitySelectorDiscoveryServiceDeltaIdentitySelectorsClient) Send(m *v3.DeltaDiscoveryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *identitySelectorDiscoveryServiceDeltaIdentitySelectorsClient) Recv() (*v3.DeltaDiscoveryResponse, error) {
	m := new(v3.DeltaDiscoveryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *identitySelectorDiscoveryServiceClient) FetchIdentitySelectors(ctx context.Context, in *v3.DiscoveryRequest, opts ...grpc.CallOption) (*v3.DiscoveryResponse, error) {
	out := new(v3.DiscoveryResponse)
	err := c.cc.Invoke(ctx, "/cilium.IdentitySelectorDiscoveryService/FetchIdentitySelectors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentitySelectorDiscoveryServiceServer is the server API for IdentitySelectorDiscoveryService service.
type IdentitySelectorDiscoveryServiceServer interface {
	StreamIdentitySelectors(IdentitySelectorDiscoveryService_StreamIdentitySelectorsServer) error
	DeltaIdentitySelectors(IdentitySelectorDiscoveryService_DeltaIdentitySelectorsServer) error
	FetchIdentitySelectors(context.Context, *v3.DiscoveryRequest) (*v3.DiscoveryResponse, error)
}

// UnimplementedIdentitySelectorDiscoveryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIdentitySelectorDiscoveryServiceServer struct {
}

func (*UnimplementedIdentitySelectorDiscoveryServiceServer) StreamIdentitySelectors(IdentitySelectorDiscoveryService_StreamIdentitySelectorsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamIdentitySelectors not implemented")
}
func (*UnimplementedIdentitySelectorDiscoveryServiceServer) DeltaIdentitySelectors(IdentitySelectorDiscoveryService_DeltaIdentitySelectorsServer) error {
	return status.Errorf(codes.Unimplemented, "method DeltaIdentitySelectors not implemented")
}
func (*UnimplementedIdentitySelectorDiscoveryServiceServer) FetchIdentitySelectors(context.Context, *v3.DiscoveryRequest) (*v3.DiscoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchIdentitySelectors not implemented")
}

func RegisterIdentitySelectorDiscoveryServiceServer(s *grpc.Server, srv IdentitySelectorDiscoveryServiceServer) {
	s.RegisterService(&_IdentitySelectorDiscoveryService_serviceDesc, srv)
}

func _IdentitySelectorDiscoveryService_StreamIdentitySelectors_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IdentitySelectorDiscoveryServiceServer).StreamIdentitySelectors(&identitySelectorDiscoveryServiceStreamIdentitySelectorsServer{stream})
}

type IdentitySelectorDiscoveryService_StreamIdentitySelectorsServer interface {
	Send(*v3.DiscoveryResponse) error
	Recv() (*v3.DiscoveryRequest, error)
	grpc.ServerStream
}

type identitySelectorDiscoveryServiceStreamIdentitySelectorsServer struct {
	grpc.ServerStream
}

func (x *identitySelectorDiscoveryServiceStreamIdentitySelectorsServer) Send(m *v3.DiscoveryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *identitySelectorDiscoveryServiceStreamIdentitySelectorsServer) Recv() (*v3.DiscoveryRequest, error) {
	m := new(v3.DiscoveryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IdentitySelectorDiscoveryService_DeltaIdentitySelectors_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IdentitySelectorDiscoveryServiceServer).DeltaIdentitySelectors(&identitySelectorDiscoveryServiceDeltaIdentitySelectorsServer{stream})
}

type IdentitySelectorDiscoveryService_DeltaIdentitySelectorsServer interface {
	Send(*v3.DeltaDiscoveryResponse) error
	Recv() (*v3.DeltaDiscoveryRequest, error)
	grpc.ServerStream
}

type identitySelectorDiscoveryServiceDeltaIdentitySelectorsServer struct {
	grpc.ServerStream
}

func (x *identitySelectorDiscoveryServiceDeltaIdentitySelectorsServer) Send(m *v3.DeltaDiscoveryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *identitySelectorDiscoveryServiceDeltaIdentitySelectorsServer) Recv() (*v3.DeltaDiscoveryRequest, error) {
	m := new(v3.DeltaDiscoveryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _IdentitySelectorDiscoveryService_FetchIdentitySelectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v3.DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentitySelectorDiscoveryServiceServer).FetchIdentitySelectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cilium.IdentitySelectorDiscoveryService/FetchIdentitySelectors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentitySelectorDiscoveryServiceServer).FetchIdentitySelectors(ctx, req.(*v3.DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentitySelectorDiscoveryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cilium.IdentitySelectorDiscoveryService",
	HandlerType: (*IdentitySelectorDiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchIdentitySelectors",
			Handler:    _IdentitySelectorDiscoveryService_FetchIdentitySelectors_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIdentitySelectors",
			Handler:       _IdentitySelectorDiscoveryService_StreamIdentitySelectors_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DeltaIdentitySelectors",
			Handler:       _IdentitySelectorDiscoveryService_DeltaIdentitySelectors_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cilium/api/isds.proto",
}
